### ISSUE TITLE
Verify if we are affected by GHSA-p6mc-m468-83gw

### ISSUE THREAD

**Issue by MarwaAbdallah** [trustbloc/talks#38]
@rolsonquadras @llorllale 
We received this advisory. Can you please verify that we are affected, as well as fix the issue if we are ? Thanks.

![image](https://user-images.githubusercontent.com/7713988/87949571-30aeca80-ca74-11ea-9f7c-944ff5a550c7.png)

**Comment by llorllale** [comment]
@MarwaAbdallah patches #36 and #37 submitted, will be merged shortly
